### ISSUE TITLE
Rule ChangeConditionalReturnedCellRector not applied

### ISSUE THREAD

**Issue by Fly06-Fr** [rectorphp/rector-phpoffice#27]
Hello,

I am currently migrating my old phpexcel code the phpoffice/phpspreadsheet (better late than never ;-).

However, I encountered the following problem: rule ChangeConditionalReturnedCellRector is not applied where it should be.

**Rector config file :**

------------------ start rector.php -------------------------
```
<?php
declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\PHPOffice\Rector\MethodCall\ChangeConditionalReturnedCellRector;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->rule(ChangeConditionalReturnedCellRector::class);
};
```
------------------ end rector.php ---------------------------

**Sample code :**

------------------ start rector.testfile.php ------------------
```
<?php

$workbook = new PHPExcel();
$sheet = $workbook->getActiveSheet();
$sheet->setCellValue('A1', 'Hello rector!');

unset($workbook);
```
------------------ end rector.testfile.php --------------------

**Command-line execution :**

------------------ start command-line -------------------------
```
rector process rector.testfile.php --dry-run --debug
rector.testfile.php
[file] rector.testfile.php
[rule] Rector\PHPOffice\Rector\MethodCall\ChangeConditionalReturnedCellRector

[file] rector.testfile.php
[rule] Rector\PHPOffice\Rector\MethodCall\ChangeConditionalReturnedCellRector


                                                                                                                        
 [OK] Rector is done!  
```                                          
------------------ end command-line ----------------------------

I was expected line:
`$sheet->setCellValue('A1', 'Hello rector!');`
to be changed to:
`$sheet->getCell('A1')->setValue('Hello rector!');`

But nothing happened.

I investigated a little bit and found that the rule was not applied because rector did not find any node of type 'PHPExcel_Worksheet'.

**Questions :**

Am I doing something wrong (I have no prior experience with rector)? 
Am I missing something important in my rector config file?

Any help would be greatly appreciated, thanks.

**Comment by samsonasik** [comment]
This package is discontinued, new package is needed :). Feel free to create one.
