### ISSUE TITLE
install issue: [ERROR] Class "Rector\Doctrine\Set\PHPOfficeSetList" not found

### ISSUE THREAD

**Issue by jlt911** [rectorphp/rector-phpoffice#9]
Hi,
I'm new to rector. I'm trying to use it to convert some php-excel programs to phpspreadsheet.
The basic installation instructions don't work.
Here is what I did:
-created a new folder and install using the command : composer require rector/rector --dev  (see image 1)
-created a rector.php file with the content copied from the install page (see image 2)
-created a src folder and put an excel report to be processed
-ran the command : vendor\bin\rector process src (see image 3)
I get this error : [ERROR] Class "Rector\Doctrine\Set\PHPOfficeSetList" not found

What did I missed ? This is on windows 10 with wamp server. See attached screen captures.
Thank you
![rector1](https://user-images.githubusercontent.com/20934940/145666807-b0983611-a0fc-41bf-9485-1d38c93cb167.png)
![rector2](https://user-images.githubusercontent.com/20934940/145666809-530d018d-bcb5-4807-b614-06581bca4b13.png)
![rector3](https://user-images.githubusercontent.com/20934940/145666810-19a1a886-733f-42ab-ae3d-6e7625a3b0d2.png)
.

**Comment by samsonasik** [comment]
that's typo in readme, you can use : 

```bash
use Rector\PHPOffice\Set\PHPOfficeSetList;
```
